<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="24" passed="1" failed="23" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-08T07:43:01 IST" name="Default suite" finished-at="2024-09-08T07:48:33 IST" duration-ms="331849">
    <groups>
    </groups>
    <test started-at="2024-09-08T07:43:01 IST" name="Default test" finished-at="2024-09-08T07:48:33 IST" duration-ms="331849">
      <class name="com.tutorialsninja.qa.Test.Register">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:01 IST" name="setup" finished-at="2024-09-08T07:43:07 IST" duration-ms="5768" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_018verifyFieldRequirementsAccordingToTheClient()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:07 IST" name="TC_RF_018verifyFieldRequirementsAccordingToTheClient" finished-at="2024-09-08T07:43:08 IST" duration-ms="1555" status="FAIL">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[Cannot parse null string]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: Cannot parse null string
at java.base/java.lang.Integer.parseInt(Integer.java:624)
at java.base/java.lang.Byte.parseByte(Byte.java:195)
at java.base/java.lang.Byte.parseByte(Byte.java:221)
at com.tutorialsninja.qa.Test.Register.TC_RF_018verifyFieldRequirementsAccordingToTheClient(Register.java:655)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_018verifyFieldRequirementsAccordingToTheClient -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:08 IST" name="teardown" finished-at="2024-09-08T07:43:12 IST" duration-ms="3536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:12 IST" name="setup" finished-at="2024-09-08T07:43:17 IST" duration-ms="5036" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_001VerifyRegisteringAccountbyMandatoryfields()[pri:1, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:17 IST" name="TC_RF_001VerifyRegisteringAccountbyMandatoryfields" finished-at="2024-09-08T07:43:21 IST" duration-ms="4504" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_001VerifyRegisteringAccountbyMandatoryfields -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:21 IST" name="teardown" finished-at="2024-09-08T07:43:25 IST" duration-ms="3483" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:25 IST" name="setup" finished-at="2024-09-08T07:43:31 IST" duration-ms="5874" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_002VerifyMessageSentToRegisteredEmail()[pri:2, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:31 IST" name="TC_RF_002VerifyMessageSentToRegisteredEmail" finished-at="2024-09-08T07:43:35 IST" duration-ms="4357" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_002VerifyMessageSentToRegisteredEmail(Register.java:109)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_002VerifyMessageSentToRegisteredEmail -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:35 IST" name="teardown" finished-at="2024-09-08T07:43:38 IST" duration-ms="3531" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:38 IST" name="setup" finished-at="2024-09-08T07:43:44 IST" duration-ms="5158" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_003VerifyRegisteringAccountbyAllfields()[pri:3, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:44 IST" name="TC_RF_003VerifyRegisteringAccountbyAllfields" finished-at="2024-09-08T07:43:48 IST" duration-ms="4119" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_003VerifyRegisteringAccountbyAllfields(Register.java:135)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_003VerifyRegisteringAccountbyAllfields -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:48 IST" name="teardown" finished-at="2024-09-08T07:43:51 IST" duration-ms="3606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:51 IST" name="setup" finished-at="2024-09-08T07:43:56 IST" duration-ms="4951" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_004VerifyNotificationMessagesForMandatoryFieldsWhenSubmitIsClickedWithEmptyForm()[pri:4, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:56 IST" name="TC_RF_004VerifyNotificationMessagesForMandatoryFieldsWhenSubmitIsClickedWithEmptyForm" finished-at="2024-09-08T07:43:59 IST" duration-ms="2567" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_004VerifyNotificationMessagesForMandatoryFieldsWhenSubmitIsClickedWithEmptyForm(Register.java:182)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_004VerifyNotificationMessagesForMandatoryFieldsWhenSubmitIsClickedWithEmptyForm -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:43:59 IST" name="teardown" finished-at="2024-09-08T07:44:02 IST" duration-ms="3546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:02 IST" name="setup" finished-at="2024-09-08T07:44:07 IST" duration-ms="4162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_005VerifyRegisteringAnAccountWhenYesOptionisSelectedforNewsletterField()[pri:5, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:07 IST" name="TC_RF_005VerifyRegisteringAnAccountWhenYesOptionisSelectedforNewsletterField" finished-at="2024-09-08T07:44:11 IST" duration-ms="4740" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_003VerifyRegisteringAccountbyAllfields(Register.java:135)
at com.tutorialsninja.qa.Test.Register.TC_RF_005VerifyRegisteringAnAccountWhenYesOptionisSelectedforNewsletterField(Register.java:188)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_005VerifyRegisteringAnAccountWhenYesOptionisSelectedforNewsletterField -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:11 IST" name="teardown" finished-at="2024-09-08T07:44:15 IST" duration-ms="3644" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:15 IST" name="setup" finished-at="2024-09-08T07:44:20 IST" duration-ms="4945" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_006VerifyRegisteringAnAccountWhenNoOptionisSelectedforNewsletterField()[pri:6, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:20 IST" name="TC_RF_006VerifyRegisteringAnAccountWhenNoOptionisSelectedforNewsletterField" finished-at="2024-09-08T07:44:24 IST" duration-ms="4101" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_001VerifyRegisteringAccountbyMandatoryfields(Register.java:96)
at com.tutorialsninja.qa.Test.Register.TC_RF_006VerifyRegisteringAnAccountWhenNoOptionisSelectedforNewsletterField(Register.java:199)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_006VerifyRegisteringAnAccountWhenNoOptionisSelectedforNewsletterField -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:24 IST" name="teardown" finished-at="2024-09-08T07:44:28 IST" duration-ms="3506" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:28 IST" name="setup" finished-at="2024-09-08T07:44:32 IST" duration-ms="4028" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_007VerifyDifferentWaysOfNavigatingToRegisterAccountPage()[pri:7, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:32 IST" name="TC_RF_007VerifyDifferentWaysOfNavigatingToRegisterAccountPage" finished-at="2024-09-08T07:44:34 IST" duration-ms="2565" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_007VerifyDifferentWaysOfNavigatingToRegisterAccountPage(Register.java:236)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_007VerifyDifferentWaysOfNavigatingToRegisterAccountPage -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:34 IST" name="teardown" finished-at="2024-09-08T07:44:38 IST" duration-ms="3479" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:38 IST" name="setup" finished-at="2024-09-08T07:44:43 IST" duration-ms="4939" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_008VerifyRegisteringAnAccountWithDifferentPasswordsInto_Password_And_PasswordConfirm_Fields()[pri:8, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:43 IST" name="TC_RF_008VerifyRegisteringAnAccountWithDifferentPasswordsInto_Password_And_PasswordConfirm_Fields" finished-at="2024-09-08T07:44:47 IST" duration-ms="4263" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_008VerifyRegisteringAnAccountWithDifferentPasswordsInto_Password_And_PasswordConfirm_Fields(Register.java:270)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_008VerifyRegisteringAnAccountWithDifferentPasswordsInto_Password_And_PasswordConfirm_Fields -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:47 IST" name="teardown" finished-at="2024-09-08T07:44:51 IST" duration-ms="3752" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:51 IST" name="setup" finished-at="2024-09-08T07:44:56 IST" duration-ms="5294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_009VerifyRegisteringAnAccountByProvidingTheExistingAccountDetails_EXAMPLE_ExistingEmailAddress()[pri:9, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:44:56 IST" name="TC_RF_009VerifyRegisteringAnAccountByProvidingTheExistingAccountDetails_EXAMPLE_ExistingEmailAddress" finished-at="2024-09-08T07:45:01 IST" duration-ms="5210" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_009VerifyRegisteringAnAccountByProvidingTheExistingAccountDetails_EXAMPLE_ExistingEmailAddress(Register.java:303)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_009VerifyRegisteringAnAccountByProvidingTheExistingAccountDetails_EXAMPLE_ExistingEmailAddress -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:45:01 IST" name="teardown" finished-at="2024-09-08T07:45:05 IST" duration-ms="3557" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:45:05 IST" name="setup" finished-at="2024-09-08T07:45:09 IST" duration-ms="4793" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_010VerifyRegisteringAnAccountWithInvalidEmailAddress()[pri:10, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:45:09 IST" name="TC_RF_010VerifyRegisteringAnAccountWithInvalidEmailAddress" finished-at="2024-09-08T07:45:13 IST" duration-ms="3952" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_010VerifyRegisteringAnAccountWithInvalidEmailAddress(Register.java:351)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_010VerifyRegisteringAnAccountWithInvalidEmailAddress -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:45:13 IST" name="teardown" finished-at="2024-09-08T07:45:17 IST" duration-ms="3612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:45:17 IST" name="setup" finished-at="2024-09-08T07:45:21 IST" duration-ms="3804" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_011VerifyRegisteringAnAccountWithInvalidPhoneNumber()[pri:11, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:45:21 IST" name="TC_RF_011VerifyRegisteringAnAccountWithInvalidPhoneNumber" finished-at="2024-09-08T07:45:25 IST" duration-ms="4466" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_011VerifyRegisteringAnAccountWithInvalidPhoneNumber(Register.java:390)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_011VerifyRegisteringAnAccountWithInvalidPhoneNumber -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:45:25 IST" name="teardown" finished-at="2024-09-08T07:45:29 IST" duration-ms="3663" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:45:29 IST" name="setup" finished-at="2024-09-08T07:45:34 IST" duration-ms="4710" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_012VerifyRegisteringAnAccountuUsingTheKeyboardkeys()[pri:12, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:45:34 IST" name="TC_RF_012VerifyRegisteringAnAccountuUsingTheKeyboardkeys" finished-at="2024-09-08T07:45:58 IST" duration-ms="24514" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Failed to navigate to the specified element.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Failed to navigate to the specified element.
at com.tutorialsninja.qa.Utilities.Utilities.NavigateUsingTAB2(Utilities.java:59)
at com.tutorialsninja.qa.Utilities.Utilities.NavigateUsingTABAndClick(Utilities.java:69)
at com.tutorialsninja.qa.Test.Register.TC_RF_012VerifyRegisteringAnAccountuUsingTheKeyboardkeys(Register.java:425)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_012VerifyRegisteringAnAccountuUsingTheKeyboardkeys -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:45:58 IST" name="teardown" finished-at="2024-09-08T07:46:02 IST" duration-ms="3509" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:02 IST" name="setup" finished-at="2024-09-08T07:46:06 IST" duration-ms="4462" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_013VerifyAllFieldHaveingtTheProperPlaceholders()[pri:13, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:06 IST" name="TC_RF_013VerifyAllFieldHaveingtTheProperPlaceholders" finished-at="2024-09-08T07:46:08 IST" duration-ms="1594" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_013VerifyAllFieldHaveingtTheProperPlaceholders(Register.java:468)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_013VerifyAllFieldHaveingtTheProperPlaceholders -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:08 IST" name="teardown" finished-at="2024-09-08T07:46:11 IST" duration-ms="3589" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:11 IST" name="setup" finished-at="2024-09-08T07:46:16 IST" duration-ms="4840" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_014VerifymandatoryFieldsMarkedWithredcolorStarSymbol()[pri:14, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:16 IST" name="TC_RF_014VerifymandatoryFieldsMarkedWithredcolorStarSymbol" finished-at="2024-09-08T07:46:27 IST" duration-ms="11259" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"//b[text()='Privacy Policy']/ancestor::label[@for='input-privacypolicy']"}
  (Session info: chrome=128.0.6613.120)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.4'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d73810f931e2c2f2c2fd8a5d25e7c1cf, findElement {using=xpath, value=//b[text()='Privacy Policy']/ancestor::label[@for='input-privacypolicy']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 128.0.6613.120, chrome: {chromedriverVersion: 128.0.6613.119 (6e439cfca4d..., userDataDir: C:/ChromeDev}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:57792}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57792/devtoo..., se:cdpVersion: 128.0.6613.120, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d73810f931e2c2f2c2fd8a5d25e7c1cf]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//b[text()='Privacy Policy']/ancestor::label[@for='input-privacypolicy']"}
  (Session info: chrome=128.0.6613.120)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.4'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d73810f931e2c2f2c2fd8a5d25e7c1cf, findElement {using=xpath, value=//b[text()='Privacy Policy']/ancestor::label[@for='input-privacypolicy']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 128.0.6613.120, chrome: {chromedriverVersion: 128.0.6613.119 (6e439cfca4d..., userDataDir: C:/ChromeDev}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:57792}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57792/devtoo..., se:cdpVersion: 128.0.6613.120, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d73810f931e2c2f2c2fd8a5d25e7c1cf
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:349)
at com.tutorialsninja.qa.Test.Register.TC_RF_014VerifymandatoryFieldsMarkedWithredcolorStarSymbol(Register.java:492)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_014VerifymandatoryFieldsMarkedWithredcolorStarSymbol -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:27 IST" name="teardown" finished-at="2024-09-08T07:46:31 IST" duration-ms="3449" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:31 IST" name="setup" finished-at="2024-09-08T07:46:35 IST" duration-ms="3971" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_016VerifyTheMandatoryfieldsAreAcceptingOnlySpaces()[pri:15, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:35 IST" name="TC_RF_016VerifyTheMandatoryfieldsAreAcceptingOnlySpaces" finished-at="2024-09-08T07:46:50 IST" duration-ms="14889" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_016VerifyTheMandatoryfieldsAreAcceptingOnlySpaces(Register.java:629)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_016VerifyTheMandatoryfieldsAreAcceptingOnlySpaces -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:50 IST" name="teardown" finished-at="2024-09-08T07:46:54 IST" duration-ms="4094" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:54 IST" name="setup" finished-at="2024-09-08T07:46:58 IST" duration-ms="3808" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_017VerifyPasswordfieldsInRegisterAccountPagefollowingPasswordComplexityStandards()[pri:16, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:58 IST" name="TC_RF_017VerifyPasswordfieldsInRegisterAccountPagefollowingPasswordComplexityStandards" finished-at="2024-09-08T07:46:58 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_017VerifyPasswordfieldsInRegisterAccountPagefollowingPasswordComplexityStandards(Register.java:637)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_017VerifyPasswordfieldsInRegisterAccountPagefollowingPasswordComplexityStandards -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:46:58 IST" name="teardown" finished-at="2024-09-08T07:47:01 IST" duration-ms="3444" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:01 IST" name="setup" finished-at="2024-09-08T07:47:06 IST" duration-ms="5004" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_019VerifyLeadingAndTrailingSpacesEnteredAreTrimmed()[pri:17, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:06 IST" name="TC_RF_019VerifyLeadingAndTrailingSpacesEnteredAreTrimmed" finished-at="2024-09-08T07:47:06 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_019VerifyLeadingAndTrailingSpacesEnteredAreTrimmed(Register.java:731)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_019VerifyLeadingAndTrailingSpacesEnteredAreTrimmed -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:06 IST" name="teardown" finished-at="2024-09-08T07:47:10 IST" duration-ms="3417" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:10 IST" name="setup" finished-at="2024-09-08T07:47:15 IST" duration-ms="5378" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_020VerifyPrivacyPolicyIsNotSelectedByDefaault()[pri:18, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:15 IST" name="TC_RF_020VerifyPrivacyPolicyIsNotSelectedByDefaault" finished-at="2024-09-08T07:47:16 IST" duration-ms="1042" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_020VerifyPrivacyPolicyIsNotSelectedByDefaault(Register.java:753)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_020VerifyPrivacyPolicyIsNotSelectedByDefaault -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:16 IST" name="teardown" finished-at="2024-09-08T07:47:19 IST" duration-ms="3519" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:19 IST" name="setup" finished-at="2024-09-08T07:47:24 IST" duration-ms="4843" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_021verifyRegisteringTheAccountWithoutSelectingThePrivacyPolicyCheckbox()[pri:19, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:24 IST" name="TC_RF_021verifyRegisteringTheAccountWithoutSelectingThePrivacyPolicyCheckbox" finished-at="2024-09-08T07:47:28 IST" duration-ms="4156" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false],
The warning message text does not match the expected text. expected [null] but found [Warning: You must agree to the Privacy Policy!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false],
The warning message text does not match the expected text. expected [null] but found [Warning: You must agree to the Privacy Policy!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_021verifyRegisteringTheAccountWithoutSelectingThePrivacyPolicyCheckbox(Register.java:796)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_021verifyRegisteringTheAccountWithoutSelectingThePrivacyPolicyCheckbox -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:28 IST" name="teardown" finished-at="2024-09-08T07:47:32 IST" duration-ms="3547" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:32 IST" name="setup" finished-at="2024-09-08T07:47:37 IST" duration-ms="5170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_022verifyPasswordFieldVisibilityToggle()[pri:20, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:37 IST" name="TC_RF_022verifyPasswordFieldVisibilityToggle" finished-at="2024-09-08T07:47:37 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false],
The warning message text does not match the expected text. expected [null] but found [Warning: You must agree to the Privacy Policy!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false],
The warning message text does not match the expected text. expected [null] but found [Warning: You must agree to the Privacy Policy!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_022verifyPasswordFieldVisibilityToggle(Register.java:847)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_022verifyPasswordFieldVisibilityToggle -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:37 IST" name="teardown" finished-at="2024-09-08T07:47:41 IST" duration-ms="3582" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:41 IST" name="setup" finished-at="2024-09-08T07:47:45 IST" duration-ms="4054" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_023VerifyNavigateToAllLinksInRegisterPage()[pri:21, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:47:45 IST" name="TC_RF_023VerifyNavigateToAllLinksInRegisterPage" finished-at="2024-09-08T07:48:07 IST" duration-ms="22429" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false],
The warning message text does not match the expected text. expected [null] but found [Warning: You must agree to the Privacy Policy!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false],
The warning message text does not match the expected text. expected [null] but found [Warning: You must agree to the Privacy Policy!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_023VerifyNavigateToAllLinksInRegisterPage(Register.java:886)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_023VerifyNavigateToAllLinksInRegisterPage -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:48:07 IST" name="teardown" finished-at="2024-09-08T07:48:11 IST" duration-ms="3597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:48:11 IST" name="setup" finished-at="2024-09-08T07:48:15 IST" duration-ms="4284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_024verifyPasswordFieldRequiredWithoutPasswordConfirm()[pri:22, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:48:15 IST" name="TC_RF_024verifyPasswordFieldRequiredWithoutPasswordConfirm" finished-at="2024-09-08T07:48:20 IST" duration-ms="4468" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false],
The warning message text does not match the expected text. expected [null] but found [Warning: You must agree to the Privacy Policy!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false],
The warning message text does not match the expected text. expected [null] but found [Warning: You must agree to the Privacy Policy!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_024verifyPasswordFieldRequiredWithoutPasswordConfirm(Register.java:926)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_024verifyPasswordFieldRequiredWithoutPasswordConfirm -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:48:20 IST" name="teardown" finished-at="2024-09-08T07:48:23 IST" duration-ms="3495" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:48:23 IST" name="setup" finished-at="2024-09-08T07:48:28 IST" duration-ms="4824" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TC_RF_025VerifyTheBreadcrumbPageHeadingPageURLPageTitleOfRegisterAccountPage()[pri:23, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:48:28 IST" name="TC_RF_025VerifyTheBreadcrumbPageHeadingPageURLPageTitleOfRegisterAccountPage" finished-at="2024-09-08T07:48:29 IST" duration-ms="955" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false],
The warning message text does not match the expected text. expected [null] but found [Warning: You must agree to the Privacy Policy!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false],
Expected registration to fail due to invalid phone number, but success page was displayed. expected [true] but found [false],
Failed due to Warning message for field: telePhone is not displayed expected [true] but found [false],
Failed due to Warning message for field: Password is not displayed expected [true] but found [false],
The warning message text does not match the expected text. expected [null] but found [Warning: You must agree to the Privacy Policy!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tutorialsninja.qa.Test.Register.TC_RF_025VerifyTheBreadcrumbPageHeadingPageURLPageTitleOfRegisterAccountPage(Register.java:964)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_RF_025VerifyTheBreadcrumbPageHeadingPageURLPageTitleOfRegisterAccountPage -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.tutorialsninja.qa.Test.Register@2034b64c]" started-at="2024-09-08T07:48:29 IST" name="teardown" finished-at="2024-09-08T07:48:32 IST" duration-ms="3613" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.tutorialsninja.qa.Test.Register -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
